component_depth: 3
languages:
  - name: typescript
    production:
      include:
        - /src/.*\.ts
      exclude:
        - /src/index\.ts
        - /src/config\.ts
    test:
      include:
        - /tests/.*\.ts
